Replace vertex buffers with stable solution
ldtteam/Structurize pull request #119
Opened 2020-04-11 06:59 UTC by Nightenom

# Changes proposed in this pull request:
- fix memory leak caused by vertex buffers

Review please

2020-04-11 07:02 UTC, marchermans requested changes
This is still leaving the buffers open when the user changes rotation or mirroring of a schematic!

2020-04-14 09:55 UTC, marchermans requested changes
No this needs to happen at the top. Else u ou delete the data from the gpu again.

2020-04-14 10:26 UTC, Nightenom commented
> No this needs to happen at the top. Else u ou delete the data from the gpu again.

Hmm?

2020-04-14 12:55 UTC, marchermans approved these changes

2020-04-14 12:55 UTC, merged