Render stacks
ldtteam/Structurize pull request #147
Opened 2020-05-28 12:11 UTC by Raycoms

Closes #
Closes #
Closes #

# Changes proposed in this pull request:
-
-
-

Review please

2020-05-30 15:07 UTC, marchermans approved these changes

2020-05-30 16:58 UTC, Nightenom requested changes
Probably remove empty drawSelfLast overrides where it's unnecessary

2020-05-30 16:58 UTC, Nightenom commented on src/main/java/com/ldtteam/blockout/views/View.java
> +        return mousePointableEventHandler(mx, my, (child, mxChild, myChild) -> child.scrollInput(wheel, mxChild, myChild), null);
I think you want to unhover here too. User may scroll without moving the mouse.

2020-05-30 16:58 UTC, Nightenom commented on src/main/java/com/ldtteam/blockout/controls/Scrollbar.java
> +        };
semicolon

2020-06-01 15:50 UTC, marchermans approved these changes

2020-06-01 18:52 UTC, merged