Schematic loading offthread
ldtteam/Structurize pull request #198
Opened 2020-08-08 12:45 UTC by someaddons

Move schematic loading offthread to no longer cause long delays on logging/startups

Review please

2020-08-08 12:57 UTC, Nightenom requested changes
I'm ok with this for client, for server this definitely needs joining before players can connect. (For client it would be cool to join that before player tries to connect or before main menu screen)
In which load phase this happens?

2020-08-08 12:57 UTC, Nightenom commented on src/main/java/com/ldtteam/structurize/management/Structures.java
> +    private static ThreadPoolExecutor executor = (ThreadPoolExecutor) Executors.newCachedThreadPool();
Can we use vanilla thread executor?

2020-08-08 12:57 UTC, Nightenom commented on src/main/java/com/ldtteam/structurize/management/Structures.java
> +        executor.submit(() -> loadStyleMaps());
Add boolean and make it synchronous by default (because of reload method below).

2020-08-16 15:34 UTC, malte0811 commented
I have some profiling data for this from logging into ForgeCraft, nearly all of the time is in `StructureLoadingUtils#getStream`:
![image](https://user-images.githubusercontent.com/10406104/90337778-06a1e700-dfe5-11ea-957a-3825c877b1c2.png)

About 40% that time will probably be fixed by https://github.com/MinecraftForge/MinecraftForge/pull/7256. The rest is mostly spent in [this method](https://github.com/MinecraftForge/MinecraftForge/blob/1.16.x/src/fmllauncher/java/net/minecraftforge/fml/loading/LoadingModList.java#L121-L136), so that part of the time grows linearly with mod count. I don't know whether using resource/data pack methods is possible here, they do currently have the same issue but will be fixed with https://github.com/MinecraftForge/MinecraftForge/pull/7228.

 You're currently calling `getStream` twice on (as far as I can tell) the same file, so you can get rid of half the time easily by just storing the file contents in memory.

2020-08-16 15:49 UTC, someaddons commented
ye this is where it loads schematics from file, and as we have quite a lot ~3400+ it takes a while

2020-08-16 16:21 UTC, malte0811 commented
It probably wouldn't "take a while" without the Forge issues (and only opening the files once). The first one I mentioned should effectively get rid of those 40%, and from my experience in IE using a constant-time method for getting resources can give a factor 10 improvement in larger packs (see https://github.com/MinecraftForge/MinecraftForge/issues/7227).

2020-08-16 16:31 UTC, Raycoms commented
@Nightenom what is the worst that can happen here? Schematic missing when opening build tool?

2020-08-16 16:32 UTC, Raycoms commented
When she restarts does it fix it?

2020-08-18 06:57 UTC, malte0811 commented
[This patch](https://gist.github.com/malte0811/feec55ca151f13f99618654a2b258a09) gets structure loading time for MineColonies down to <3 seconds when joining FC (from 30-40 seconds). I applied the patch to cd556d705b4d6dec310321e5765e979efa1edf4d, the last 1.16.1 commit. I'm not sure whether you'll want that code (it does a lot of things manually that happen automatically otherwise), if you do you can either just apply the patch directly or I can create a PR. The latter would probably be a good idea since the code style is a wild mix of IEs style, Structurize's style and my own style. The `ThreadLocal`s might be unnecessary, I don't know whether the code is called on multiple threads and `ThreadLocal` is cheap enough for me to be happy using it for testing.

2020-08-18 07:19 UTC, Nightenom commented
@malte0811 looks hell promising, it's kinda funny how long does it take for forge to discover ModFile. We will take your idea and put it into next PR, will mention you in commits. Thanks for your time and work you have put into this

2020-08-18 07:19 UTC, Nightenom commented
Closing this since there is better single thread solution

2020-08-18 07:19 UTC, closed without merging