Fix items not being put into chests.
ldtteam/Structurize pull request #384
Opened 2021-06-03 13:07 UTC by uecasm

Closes #383

# Changes proposed in this pull request:
- Fixes chests being placed empty.

Review please

Removing that redundant bit of code (the return value is ignored, the only thing it does is to throw an exception and return because it was given the wrong world) fixes everything.  The chest is populated as expected.  Double chests also work as expected and don't duplicate anything, no matter what rotation is used.  The only thing that continues to not work is mirroring a double chest -- but even then it has the right items, it just doesn't connect properly (which is not new).

2021-06-03 13:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ldtteam/Structurize?pullRequest=384) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ldtteam/Structurize?pullRequest=384) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ldtteam/Structurize?pullRequest=384) it.</sub>

2021-06-03 13:10 UTC, Raycoms requested changes
No, this is here on purpose, if you remove this, players can infinitely dupe items having the builder build chests with content in them.

2021-06-03 13:11 UTC, uecasm commented
Why?  The builder should demand the items that are in the inventory.  But that would have to happen elsewhere, because this bit of code can't possibly report that anyway.

2021-06-03 13:12 UTC, uecasm commented
`getRequiredItems` is an entirely separate code path.

2021-06-03 13:13 UTC, Raycoms commented
> Why? The builder should demand the items that are in the inventory. But that would have to happen elsewhere, because this bit of code can't possibly report that anyway.

The problem is this:
- In the same handler a bit below this code there is a method to query the items. Since chests suck, the items return empty.
- As such the builder won't request any items.
- As such the builder will reach this stage.
- As such, we have to detect in this stage if the items could be queried or not, and if not return an empty inventory.

2021-06-03 13:15 UTC, uecasm commented
Perhaps then this should only happen if it's a builder operation rather than a creative paste?  Because I can see this being a problem for raid ship chests too as it stands...

2021-06-03 13:16 UTC, Raycoms commented
> Perhaps then this should only happen if it's a builder operation rather than a creative paste? Because I can see this being a problem for raid ship chests too as it stands...

The solution is simply to make a propper chest handler that is only called for those vanilla containers and that AT the inventory or read the inventory from NBT such that no crash happens.

2021-06-03 13:35 UTC, uecasm commented
Ok, there, that should work.  I haven't tested this with a builder as yet (but I might try in the morning if nobody beats me to it) but I'm confident it will do the job.

2021-06-03 14:22 UTC, Raycoms submitted a review, later dismissed

2021-06-03 15:33 UTC, Nightenom submitted a review, later dismissed

2021-06-05 11:40 UTC, uecasm commented
FWIW, this `loadAllItems` call appears to be used for all of the following in vanilla:
* multiple kinds of furnaces
* barrels
* brewing stands
* campfires
* chests
* dispensers
* hoppers
* shulker boxes

The "since chests suck" code appears to be entirely added by Forge, incidentally (not present in vanilla), and as far as I can see does only affect chests and not any of the other above blocks.  Having said that, it's ultimately still a bug in Structurize where `getItemStacksOfTileEntity` is passing the wrong World and BlockState to `readTileEntity` during placement (it's passing the target world and block therein, not the blueprint); it's simply a happy accident that most TEs don't seem to care about that.  (This PR is still an improvement, but it would be good to fix the rest of it later.)

2021-06-05 13:03 UTC, Raycoms commented
> * dispensers

The thing is, that it's impossible to handle double chests otherwise. Even if we create a simulated world just for the placement of chests. We would still get duplicate items from it. As that, on purpose I don't give it the world such that it cannot get the chest. I rather have an empty inventory and place an empty inventory than allowing to dupe items.

2021-06-05 14:05 UTC, Nightenom commented
Solution to this would be proper multiblock handler imho
With the current state single block nbt parsing is the best thing I see

2021-06-05 14:11 UTC, Raycoms commented
In the "canHandle" method, we should be able to check if the tileentitydata contains regular inventory data, no?

2021-06-05 14:14 UTC, Nightenom commented
> In the "canHandle" method, we should be able to check if the tileentitydata contains regular inventory data, no?

Yeah, surely, but remember that this check should be as fast as possible

2021-06-05 14:28 UTC, Raycoms commented
if container && tenbt.containsx should match most use cases

2021-06-06 04:47 UTC, uecasm commented
Sure.  Want me to make that change?

2021-06-06 10:39 UTC, Raycoms commented
Sure

On Sun, Jun 6, 2021, 01:47 Gavin Lambert ***@***.***> wrote:

> Sure. Want me to make that change?
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/ldtteam/Structurize/pull/384#issuecomment-855336741>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABRD3S4MCGZPOEGKCCGUELTTRL4VTANCNFSM46AX4MTA>
> .
>

2021-06-06 13:10 UTC, Raycoms approved these changes
I like this

2021-06-06 15:00 UTC, Nightenom reviewed
Minor nitpick

2021-06-06 15:00 UTC, Nightenom commented on src/main/java/com/ldtteam/structurize/placement/handlers/placement/PlacementHandlers.java
> +    public static class ContainerPlacementHandler implements IPlacementHandler
Please undo the class rename, as it doesn't seem necessary

2021-06-07 00:59 UTC, uecasm commented on src/main/java/com/ldtteam/structurize/placement/handlers/placement/PlacementHandlers.java
> +    public static class ContainerPlacementHandler implements IPlacementHandler
It handles ContainerBlock, and not just ChestBlock.  The rename seems entirely necessary.

2021-06-07 01:02 UTC, Raycoms commented on src/main/java/com/ldtteam/structurize/placement/handlers/placement/PlacementHandlers.java
> +    public static class ContainerPlacementHandler implements IPlacementHandler
I agree

2021-06-07 06:45 UTC, Nightenom approved these changes

2021-06-07 06:46 UTC, merged