Replaced `"item": "minecraft:stick"`with `"tag": "forge:rods/wooden"` to allow a better compatibility with alternative sticks.
ldtteam/Structurize pull request #498
Opened 2022-03-23 17:37 UTC by MarkusBordihn

Closes 497#

# Changes proposed in this pull request:
- Replaced `"item": "minecraft:stick"` with `"tag": "forge:rods/wooden"` to allow a better compatibility with alternative sticks.
- Optional: Updated gradle wrapper to the latest version.

Review please

2022-03-23 17:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ldtteam/Structurize?pullRequest=498) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ldtteam/Structurize?pullRequest=498) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ldtteam/Structurize?pullRequest=498) it.</sub>

2022-03-23 17:48 UTC, Nightenom approved these changes, later dismissed

2022-04-03 20:14 UTC, Raycoms submitted a review, later dismissed

2022-04-04 14:16 UTC, OrionDevelopment requested changes

2022-04-04 14:16 UTC, OrionDevelopment commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-7.3.1-bin.zip
7.4 is latest.

2022-04-04 17:25 UTC, MarkusBordihn commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-7.3.1-bin.zip
Fixed.

2022-04-06 20:07 UTC, Nightenom approved these changes

2022-04-06 20:09 UTC, merged