Disables tagtool
ldtteam/Structurize pull request #638
Opened 2023-12-20 21:10 UTC by someaddons

# Changes proposed in this pull request:
-Disable tag tool useable in survival

Review please

2023-12-20 21:11 UTC, Raycoms submitted a review, later dismissed

2023-12-20 21:37 UTC, Nightenom requested changes

2023-12-20 21:37 UTC, Nightenom commented on src/main/java/com/ldtteam/structurize/network/messages/SetTagInTool.java
> +            ctxIn.getSender().displayClientMessage(Component.literal("Cannot use tag tool in survival"), false);
translation please

2023-12-20 23:13 UTC, uecasm commented
Some players rely on the tag tool being usable -- it can fix certain cases where things aren't tagged properly in the meantime before the schematic is actually fixed.

Whether it actually works or not depends on whether the tags are captured on build success (will not work post-build) or are checked as needed (will work).

2023-12-21 07:25 UTC, Raycoms commented
> Some players rely on the tag tool being usable -- it can fix certain cases where things aren't tagged properly in the meantime before the schematic is actually fixed.
> 
> Whether it actually works or not depends on whether the tags are captured on block placement (will not work post-build) or are checked as needed (will work).
> 
> Also, the scan tool is deliberately usable in survival so that players can make decorations etc, and there's several reasons why they might want to tag their decorations.

I thought about this yesterday too. For just "need fixing temporary" people can spawn it in creatively with the give command or creative menu. 

The scan tool is correctly usable in survivable and should stay. But being able to tag buildings while they are operating could allow people to potentially cheese things. E.g. infinitely extend the plantation field capacity.

2023-12-21 07:27 UTC, Thodor12 commented
Well it doesn't work for plantation fields, I can guarantee you that much since field locations are only checked on placement time.
And even then there's a hard limit per field type, if there are additional ones those are ignored.

2023-12-21 08:48 UTC, uecasm commented
> For just "need fixing temporary" people can spawn it in creatively with the give command or creative menu.

Not if they're playing in survival on a server.  Or playing SP without cheats enabled.

> But being able to tag buildings while they are operating could allow people to potentially cheese things.

Which things?  As Thodor said the plantation has built-in limits even if you add tags (and it captures tag on block placement so adding them later does nothing anyway) -- that was intended so that style authors can't break game balance either.  `invisible` and `leisure` tags will work after placement, but aren't cheesable.  I don't think any of the other tags are cheesable either.

2023-12-21 08:57 UTC, someaddons commented
Players simply should not be able to mess with internal data where they can easily break stuff

2023-12-21 09:33 UTC, merged

2023-12-21 11:18 UTC, uecasm commented
> Players simply should not be able to mess with internal data where they can easily break stuff

Despite all examples being beneficial and no examples breaking anything?  I don't agree.  Besides, if players do break things, they get to keep the pieces.  (i.e. given that it is more helpful than harmful, it is actively harmful to disable the feature, with no upside.)

2023-12-21 11:23 UTC, Raycoms commented
> > Players simply should not be able to mess with internal data where they can easily break stuff
> 
> Despite all examples being beneficial and no examples breaking anything? I don't agree. Besides, if players do break things, they get to keep the pieces. (i.e. given that it is more helpful than harmful, it is actively harmful to disable the feature, with no upside.)

I dont think a debug tool being available for crafting makes a lot of sense. People look up obtainable stuff in survival in JEI for mods and play around with it.  Its confusing for players at the least.

And, instead of telling people to fix the tag, we should fix the tag and update the mod =D